/*
Zibal API

Combined API for Zibal Gateway and Facilities (Verification, Wallet, etc.)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zibal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BankAccountToIbanRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankAccountToIbanRequest{}

// BankAccountToIbanRequest struct for BankAccountToIbanRequest
type BankAccountToIbanRequest struct {
	BankAccount string `json:"bankAccount"`
	BankCode string `json:"bankCode"`
}

type _BankAccountToIbanRequest BankAccountToIbanRequest

// NewBankAccountToIbanRequest instantiates a new BankAccountToIbanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankAccountToIbanRequest(bankAccount string, bankCode string) *BankAccountToIbanRequest {
	this := BankAccountToIbanRequest{}
	this.BankAccount = bankAccount
	this.BankCode = bankCode
	return &this
}

// NewBankAccountToIbanRequestWithDefaults instantiates a new BankAccountToIbanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankAccountToIbanRequestWithDefaults() *BankAccountToIbanRequest {
	this := BankAccountToIbanRequest{}
	return &this
}

// GetBankAccount returns the BankAccount field value
func (o *BankAccountToIbanRequest) GetBankAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankAccount
}

// GetBankAccountOk returns a tuple with the BankAccount field value
// and a boolean to check if the value has been set.
func (o *BankAccountToIbanRequest) GetBankAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankAccount, true
}

// SetBankAccount sets field value
func (o *BankAccountToIbanRequest) SetBankAccount(v string) {
	o.BankAccount = v
}

// GetBankCode returns the BankCode field value
func (o *BankAccountToIbanRequest) GetBankCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankCode
}

// GetBankCodeOk returns a tuple with the BankCode field value
// and a boolean to check if the value has been set.
func (o *BankAccountToIbanRequest) GetBankCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankCode, true
}

// SetBankCode sets field value
func (o *BankAccountToIbanRequest) SetBankCode(v string) {
	o.BankCode = v
}

func (o BankAccountToIbanRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankAccountToIbanRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bankAccount"] = o.BankAccount
	toSerialize["bankCode"] = o.BankCode
	return toSerialize, nil
}

func (o *BankAccountToIbanRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bankAccount",
		"bankCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankAccountToIbanRequest := _BankAccountToIbanRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankAccountToIbanRequest)

	if err != nil {
		return err
	}

	*o = BankAccountToIbanRequest(varBankAccountToIbanRequest)

	return err
}

type NullableBankAccountToIbanRequest struct {
	value *BankAccountToIbanRequest
	isSet bool
}

func (v NullableBankAccountToIbanRequest) Get() *BankAccountToIbanRequest {
	return v.value
}

func (v *NullableBankAccountToIbanRequest) Set(val *BankAccountToIbanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBankAccountToIbanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBankAccountToIbanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankAccountToIbanRequest(val *BankAccountToIbanRequest) *NullableBankAccountToIbanRequest {
	return &NullableBankAccountToIbanRequest{value: val, isSet: true}
}

func (v NullableBankAccountToIbanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankAccountToIbanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


