/*
Zibal API

Combined API for Zibal Gateway and Facilities (Verification, Wallet, etc.)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zibal

import (
	"encoding/json"
)

// checks if the ShahkarInquiryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShahkarInquiryResponse{}

// ShahkarInquiryResponse struct for ShahkarInquiryResponse
type ShahkarInquiryResponse struct {
	Result *int32 `json:"result,omitempty"`
	Message *string `json:"message,omitempty"`
	Data *ShahkarInquiryResponseData `json:"data,omitempty"`
}

// NewShahkarInquiryResponse instantiates a new ShahkarInquiryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShahkarInquiryResponse() *ShahkarInquiryResponse {
	this := ShahkarInquiryResponse{}
	return &this
}

// NewShahkarInquiryResponseWithDefaults instantiates a new ShahkarInquiryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShahkarInquiryResponseWithDefaults() *ShahkarInquiryResponse {
	this := ShahkarInquiryResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ShahkarInquiryResponse) GetResult() int32 {
	if o == nil || IsNil(o.Result) {
		var ret int32
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShahkarInquiryResponse) GetResultOk() (*int32, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ShahkarInquiryResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given int32 and assigns it to the Result field.
func (o *ShahkarInquiryResponse) SetResult(v int32) {
	o.Result = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ShahkarInquiryResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShahkarInquiryResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ShahkarInquiryResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ShahkarInquiryResponse) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ShahkarInquiryResponse) GetData() ShahkarInquiryResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ShahkarInquiryResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShahkarInquiryResponse) GetDataOk() (*ShahkarInquiryResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ShahkarInquiryResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ShahkarInquiryResponseData and assigns it to the Data field.
func (o *ShahkarInquiryResponse) SetData(v ShahkarInquiryResponseData) {
	o.Data = &v
}

func (o ShahkarInquiryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShahkarInquiryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableShahkarInquiryResponse struct {
	value *ShahkarInquiryResponse
	isSet bool
}

func (v NullableShahkarInquiryResponse) Get() *ShahkarInquiryResponse {
	return v.value
}

func (v *NullableShahkarInquiryResponse) Set(val *ShahkarInquiryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableShahkarInquiryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableShahkarInquiryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShahkarInquiryResponse(val *ShahkarInquiryResponse) *NullableShahkarInquiryResponse {
	return &NullableShahkarInquiryResponse{value: val, isSet: true}
}

func (v NullableShahkarInquiryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShahkarInquiryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


