/*
Zibal API

Combined API for Zibal Gateway and Facilities (Verification, Wallet, etc.)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zibal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CardToAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardToAccountRequest{}

// CardToAccountRequest struct for CardToAccountRequest
type CardToAccountRequest struct {
	CardNumber string `json:"cardNumber"`
}

type _CardToAccountRequest CardToAccountRequest

// NewCardToAccountRequest instantiates a new CardToAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardToAccountRequest(cardNumber string) *CardToAccountRequest {
	this := CardToAccountRequest{}
	this.CardNumber = cardNumber
	return &this
}

// NewCardToAccountRequestWithDefaults instantiates a new CardToAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardToAccountRequestWithDefaults() *CardToAccountRequest {
	this := CardToAccountRequest{}
	return &this
}

// GetCardNumber returns the CardNumber field value
func (o *CardToAccountRequest) GetCardNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardNumber
}

// GetCardNumberOk returns a tuple with the CardNumber field value
// and a boolean to check if the value has been set.
func (o *CardToAccountRequest) GetCardNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardNumber, true
}

// SetCardNumber sets field value
func (o *CardToAccountRequest) SetCardNumber(v string) {
	o.CardNumber = v
}

func (o CardToAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardToAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cardNumber"] = o.CardNumber
	return toSerialize, nil
}

func (o *CardToAccountRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cardNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCardToAccountRequest := _CardToAccountRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCardToAccountRequest)

	if err != nil {
		return err
	}

	*o = CardToAccountRequest(varCardToAccountRequest)

	return err
}

type NullableCardToAccountRequest struct {
	value *CardToAccountRequest
	isSet bool
}

func (v NullableCardToAccountRequest) Get() *CardToAccountRequest {
	return v.value
}

func (v *NullableCardToAccountRequest) Set(val *CardToAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCardToAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCardToAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardToAccountRequest(val *CardToAccountRequest) *NullableCardToAccountRequest {
	return &NullableCardToAccountRequest{value: val, isSet: true}
}

func (v NullableCardToAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardToAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


