/*
Zibal API

Combined API for Zibal Gateway and Facilities (Verification, Wallet, etc.)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zibal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CardToIbanRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardToIbanRequest{}

// CardToIbanRequest struct for CardToIbanRequest
type CardToIbanRequest struct {
	CardNumber string `json:"cardNumber"`
}

type _CardToIbanRequest CardToIbanRequest

// NewCardToIbanRequest instantiates a new CardToIbanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardToIbanRequest(cardNumber string) *CardToIbanRequest {
	this := CardToIbanRequest{}
	this.CardNumber = cardNumber
	return &this
}

// NewCardToIbanRequestWithDefaults instantiates a new CardToIbanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardToIbanRequestWithDefaults() *CardToIbanRequest {
	this := CardToIbanRequest{}
	return &this
}

// GetCardNumber returns the CardNumber field value
func (o *CardToIbanRequest) GetCardNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardNumber
}

// GetCardNumberOk returns a tuple with the CardNumber field value
// and a boolean to check if the value has been set.
func (o *CardToIbanRequest) GetCardNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardNumber, true
}

// SetCardNumber sets field value
func (o *CardToIbanRequest) SetCardNumber(v string) {
	o.CardNumber = v
}

func (o CardToIbanRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardToIbanRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cardNumber"] = o.CardNumber
	return toSerialize, nil
}

func (o *CardToIbanRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cardNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCardToIbanRequest := _CardToIbanRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCardToIbanRequest)

	if err != nil {
		return err
	}

	*o = CardToIbanRequest(varCardToIbanRequest)

	return err
}

type NullableCardToIbanRequest struct {
	value *CardToIbanRequest
	isSet bool
}

func (v NullableCardToIbanRequest) Get() *CardToIbanRequest {
	return v.value
}

func (v *NullableCardToIbanRequest) Set(val *CardToIbanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCardToIbanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCardToIbanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardToIbanRequest(val *CardToIbanRequest) *NullableCardToIbanRequest {
	return &NullableCardToIbanRequest{value: val, isSet: true}
}

func (v NullableCardToIbanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardToIbanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


