/*
Zibal API

Combined API for Zibal Gateway and Facilities (Verification, Wallet, etc.)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zibal

import (
	"encoding/json"
	"fmt"
)

// checks if the CardToAccountResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardToAccountResponseData{}

// CardToAccountResponseData struct for CardToAccountResponseData
type CardToAccountResponseData struct {
	Name string `json:"name"`
	BankAccount string `json:"bankAccount"`
	BankName string `json:"bankName"`
	AdditionalProperties map[string]interface{}
}

type _CardToAccountResponseData CardToAccountResponseData

// NewCardToAccountResponseData instantiates a new CardToAccountResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardToAccountResponseData(name string, bankAccount string, bankName string) *CardToAccountResponseData {
	this := CardToAccountResponseData{}
	this.Name = name
	this.BankAccount = bankAccount
	this.BankName = bankName
	return &this
}

// NewCardToAccountResponseDataWithDefaults instantiates a new CardToAccountResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardToAccountResponseDataWithDefaults() *CardToAccountResponseData {
	this := CardToAccountResponseData{}
	return &this
}

// GetName returns the Name field value
func (o *CardToAccountResponseData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CardToAccountResponseData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CardToAccountResponseData) SetName(v string) {
	o.Name = v
}

// GetBankAccount returns the BankAccount field value
func (o *CardToAccountResponseData) GetBankAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankAccount
}

// GetBankAccountOk returns a tuple with the BankAccount field value
// and a boolean to check if the value has been set.
func (o *CardToAccountResponseData) GetBankAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankAccount, true
}

// SetBankAccount sets field value
func (o *CardToAccountResponseData) SetBankAccount(v string) {
	o.BankAccount = v
}

// GetBankName returns the BankName field value
func (o *CardToAccountResponseData) GetBankName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankName
}

// GetBankNameOk returns a tuple with the BankName field value
// and a boolean to check if the value has been set.
func (o *CardToAccountResponseData) GetBankNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankName, true
}

// SetBankName sets field value
func (o *CardToAccountResponseData) SetBankName(v string) {
	o.BankName = v
}

func (o CardToAccountResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardToAccountResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["bankAccount"] = o.BankAccount
	toSerialize["bankName"] = o.BankName

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CardToAccountResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"bankAccount",
		"bankName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCardToAccountResponseData := _CardToAccountResponseData{}

	err = json.Unmarshal(data, &varCardToAccountResponseData)

	if err != nil {
		return err
	}

	*o = CardToAccountResponseData(varCardToAccountResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "bankAccount")
		delete(additionalProperties, "bankName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCardToAccountResponseData struct {
	value *CardToAccountResponseData
	isSet bool
}

func (v NullableCardToAccountResponseData) Get() *CardToAccountResponseData {
	return v.value
}

func (v *NullableCardToAccountResponseData) Set(val *CardToAccountResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCardToAccountResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCardToAccountResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardToAccountResponseData(val *CardToAccountResponseData) *NullableCardToAccountResponseData {
	return &NullableCardToAccountResponseData{value: val, isSet: true}
}

func (v NullableCardToAccountResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardToAccountResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


