/*
Zibal API

Combined API for Zibal Gateway and Facilities (Verification, Wallet, etc.)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zibal

import (
	"encoding/json"
)

// checks if the NationalIdentityInquiryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NationalIdentityInquiryResponse{}

// NationalIdentityInquiryResponse struct for NationalIdentityInquiryResponse
type NationalIdentityInquiryResponse struct {
	Result *int32 `json:"result,omitempty"`
	Message *string `json:"message,omitempty"`
	Data *NationalIdentityInquiryResponseData `json:"data,omitempty"`
}

// NewNationalIdentityInquiryResponse instantiates a new NationalIdentityInquiryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNationalIdentityInquiryResponse() *NationalIdentityInquiryResponse {
	this := NationalIdentityInquiryResponse{}
	return &this
}

// NewNationalIdentityInquiryResponseWithDefaults instantiates a new NationalIdentityInquiryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNationalIdentityInquiryResponseWithDefaults() *NationalIdentityInquiryResponse {
	this := NationalIdentityInquiryResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *NationalIdentityInquiryResponse) GetResult() int32 {
	if o == nil || IsNil(o.Result) {
		var ret int32
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NationalIdentityInquiryResponse) GetResultOk() (*int32, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *NationalIdentityInquiryResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given int32 and assigns it to the Result field.
func (o *NationalIdentityInquiryResponse) SetResult(v int32) {
	o.Result = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *NationalIdentityInquiryResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NationalIdentityInquiryResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *NationalIdentityInquiryResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *NationalIdentityInquiryResponse) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NationalIdentityInquiryResponse) GetData() NationalIdentityInquiryResponseData {
	if o == nil || IsNil(o.Data) {
		var ret NationalIdentityInquiryResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NationalIdentityInquiryResponse) GetDataOk() (*NationalIdentityInquiryResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NationalIdentityInquiryResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given NationalIdentityInquiryResponseData and assigns it to the Data field.
func (o *NationalIdentityInquiryResponse) SetData(v NationalIdentityInquiryResponseData) {
	o.Data = &v
}

func (o NationalIdentityInquiryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NationalIdentityInquiryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableNationalIdentityInquiryResponse struct {
	value *NationalIdentityInquiryResponse
	isSet bool
}

func (v NullableNationalIdentityInquiryResponse) Get() *NationalIdentityInquiryResponse {
	return v.value
}

func (v *NullableNationalIdentityInquiryResponse) Set(val *NationalIdentityInquiryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNationalIdentityInquiryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNationalIdentityInquiryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNationalIdentityInquiryResponse(val *NationalIdentityInquiryResponse) *NullableNationalIdentityInquiryResponse {
	return &NullableNationalIdentityInquiryResponse{value: val, isSet: true}
}

func (v NullableNationalIdentityInquiryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNationalIdentityInquiryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


