/*
Zibal API

Combined API for Zibal Gateway and Facilities (Verification, Wallet, etc.)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zibal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShahkarInquiryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShahkarInquiryRequest{}

// ShahkarInquiryRequest struct for ShahkarInquiryRequest
type ShahkarInquiryRequest struct {
	NationalCode string `json:"nationalCode"`
	Mobile string `json:"mobile"`
}

type _ShahkarInquiryRequest ShahkarInquiryRequest

// NewShahkarInquiryRequest instantiates a new ShahkarInquiryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShahkarInquiryRequest(nationalCode string, mobile string) *ShahkarInquiryRequest {
	this := ShahkarInquiryRequest{}
	this.NationalCode = nationalCode
	this.Mobile = mobile
	return &this
}

// NewShahkarInquiryRequestWithDefaults instantiates a new ShahkarInquiryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShahkarInquiryRequestWithDefaults() *ShahkarInquiryRequest {
	this := ShahkarInquiryRequest{}
	return &this
}

// GetNationalCode returns the NationalCode field value
func (o *ShahkarInquiryRequest) GetNationalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NationalCode
}

// GetNationalCodeOk returns a tuple with the NationalCode field value
// and a boolean to check if the value has been set.
func (o *ShahkarInquiryRequest) GetNationalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NationalCode, true
}

// SetNationalCode sets field value
func (o *ShahkarInquiryRequest) SetNationalCode(v string) {
	o.NationalCode = v
}

// GetMobile returns the Mobile field value
func (o *ShahkarInquiryRequest) GetMobile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mobile
}

// GetMobileOk returns a tuple with the Mobile field value
// and a boolean to check if the value has been set.
func (o *ShahkarInquiryRequest) GetMobileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mobile, true
}

// SetMobile sets field value
func (o *ShahkarInquiryRequest) SetMobile(v string) {
	o.Mobile = v
}

func (o ShahkarInquiryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShahkarInquiryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nationalCode"] = o.NationalCode
	toSerialize["mobile"] = o.Mobile
	return toSerialize, nil
}

func (o *ShahkarInquiryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nationalCode",
		"mobile",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShahkarInquiryRequest := _ShahkarInquiryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShahkarInquiryRequest)

	if err != nil {
		return err
	}

	*o = ShahkarInquiryRequest(varShahkarInquiryRequest)

	return err
}

type NullableShahkarInquiryRequest struct {
	value *ShahkarInquiryRequest
	isSet bool
}

func (v NullableShahkarInquiryRequest) Get() *ShahkarInquiryRequest {
	return v.value
}

func (v *NullableShahkarInquiryRequest) Set(val *ShahkarInquiryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableShahkarInquiryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableShahkarInquiryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShahkarInquiryRequest(val *ShahkarInquiryRequest) *NullableShahkarInquiryRequest {
	return &NullableShahkarInquiryRequest{value: val, isSet: true}
}

func (v NullableShahkarInquiryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShahkarInquiryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


