/*
Zibal API

Combined API for Zibal Gateway and Facilities (Verification, Wallet, etc.)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zibal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckCardWithNationalCodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckCardWithNationalCodeRequest{}

// CheckCardWithNationalCodeRequest struct for CheckCardWithNationalCodeRequest
type CheckCardWithNationalCodeRequest struct {
	NationalCode string `json:"nationalCode"`
	BirthDate string `json:"birthDate"`
	CardNumber string `json:"cardNumber"`
}

type _CheckCardWithNationalCodeRequest CheckCardWithNationalCodeRequest

// NewCheckCardWithNationalCodeRequest instantiates a new CheckCardWithNationalCodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckCardWithNationalCodeRequest(nationalCode string, birthDate string, cardNumber string) *CheckCardWithNationalCodeRequest {
	this := CheckCardWithNationalCodeRequest{}
	this.NationalCode = nationalCode
	this.BirthDate = birthDate
	this.CardNumber = cardNumber
	return &this
}

// NewCheckCardWithNationalCodeRequestWithDefaults instantiates a new CheckCardWithNationalCodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckCardWithNationalCodeRequestWithDefaults() *CheckCardWithNationalCodeRequest {
	this := CheckCardWithNationalCodeRequest{}
	return &this
}

// GetNationalCode returns the NationalCode field value
func (o *CheckCardWithNationalCodeRequest) GetNationalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NationalCode
}

// GetNationalCodeOk returns a tuple with the NationalCode field value
// and a boolean to check if the value has been set.
func (o *CheckCardWithNationalCodeRequest) GetNationalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NationalCode, true
}

// SetNationalCode sets field value
func (o *CheckCardWithNationalCodeRequest) SetNationalCode(v string) {
	o.NationalCode = v
}

// GetBirthDate returns the BirthDate field value
func (o *CheckCardWithNationalCodeRequest) GetBirthDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BirthDate
}

// GetBirthDateOk returns a tuple with the BirthDate field value
// and a boolean to check if the value has been set.
func (o *CheckCardWithNationalCodeRequest) GetBirthDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BirthDate, true
}

// SetBirthDate sets field value
func (o *CheckCardWithNationalCodeRequest) SetBirthDate(v string) {
	o.BirthDate = v
}

// GetCardNumber returns the CardNumber field value
func (o *CheckCardWithNationalCodeRequest) GetCardNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardNumber
}

// GetCardNumberOk returns a tuple with the CardNumber field value
// and a boolean to check if the value has been set.
func (o *CheckCardWithNationalCodeRequest) GetCardNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardNumber, true
}

// SetCardNumber sets field value
func (o *CheckCardWithNationalCodeRequest) SetCardNumber(v string) {
	o.CardNumber = v
}

func (o CheckCardWithNationalCodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckCardWithNationalCodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nationalCode"] = o.NationalCode
	toSerialize["birthDate"] = o.BirthDate
	toSerialize["cardNumber"] = o.CardNumber
	return toSerialize, nil
}

func (o *CheckCardWithNationalCodeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nationalCode",
		"birthDate",
		"cardNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckCardWithNationalCodeRequest := _CheckCardWithNationalCodeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckCardWithNationalCodeRequest)

	if err != nil {
		return err
	}

	*o = CheckCardWithNationalCodeRequest(varCheckCardWithNationalCodeRequest)

	return err
}

type NullableCheckCardWithNationalCodeRequest struct {
	value *CheckCardWithNationalCodeRequest
	isSet bool
}

func (v NullableCheckCardWithNationalCodeRequest) Get() *CheckCardWithNationalCodeRequest {
	return v.value
}

func (v *NullableCheckCardWithNationalCodeRequest) Set(val *CheckCardWithNationalCodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckCardWithNationalCodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckCardWithNationalCodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckCardWithNationalCodeRequest(val *CheckCardWithNationalCodeRequest) *NullableCheckCardWithNationalCodeRequest {
	return &NullableCheckCardWithNationalCodeRequest{value: val, isSet: true}
}

func (v NullableCheckCardWithNationalCodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckCardWithNationalCodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


